### ISSUE TITLE
Source files

### ISSUE THREAD

**Issue by syky27** [PrusaMK2Users/3030_Haribo_Edition#13]
Why there are no source files for parts?

This is not how open-source works...

Kinda sux, when you need to modify stuff.

**Comment by jtktam** [comment]
i starred with stl files from průša and the mk2-x project and the resultant stl files are all here.  there is no source files being withheld, almost every other printer project only release stl files and you can import them into almost any cad program if you need to.

what modification do you want to do anyways?

**Comment by ryanneufeld** [comment]
@syky27 More specifically:

As these parts were made using TinkerCAD, and online CAD package, there are no source files. Only the STL outputs.

The STL are in effect, the source.
