### ISSUE TITLE
Ease of getting the distances correct for the connection of vertical extrusions

### ISSUE THREAD

**Issue by mrjohnc** [PrusaMK2Users/3030_Haribo_Edition#19]
An common problem for the Mk2 design is getting the distance correct for attaching the vertical and horizontal sections. Can I suggest adding a 3D printed spacer to the design to take the guess work out? The spacer would fit in the groove behind the vertical section.

Thanks

**Comment by jtktam** [comment]
the design of the haribo does not need spacers because there is no way for you to do it wrong.. the distance is governed by the through hole in the extrusions. if it's unclear please join slack chat and look for jtktam
