### ISSUE TITLE
Incorrect link in BOM

### ISSUE THREAD

**Issue by Cova** [PrusaMK2Users/3030_Haribo_Edition#31]
The BOM indicates a requirement for 2x "GT2 16T pulley" - and provides a link to purchase them from RepRap Champion.  However the link sends you to a page for a 16T GT2 Idler with ball-bearings having a 3mm bore.

I believe the correct link should be: 
https://reprapchampion.com/collections/mechanical-components/products/high-quality-gt2-16t-aluminum-timing-belt-pulley-reprap-3d-printer-prusa-i3

**Comment by mihec87** [comment]
Edited and added correct link..Issue should be closed..
