### ISSUE TITLE
CodeHemi.com Down?

### ISSUE THREAD

**Issue by nrepian** [PrusaMK2Users/3030_Haribo_Edition#32]
I'd really like to mod my MK2 with these excellent 3030 Haribo extrusions, however I can't seem to be able to join the CodeHemi.com slack channel - the host appears to have been down for a few days. I've tried several times with no luck. Is there another way to access it?

**Comment by jtktam** [comment]
we are doing invite only now.. if you send me your email i will send you an invite

**Comment by nrepian** [comment]
Thanks, that would be great. I can't see a way to send you a private message on here, is there I way I can send my e-mail address without it appearing in public?

**edit: Dropped you an e-mail**

**Comment by rdsmith24** [comment]
Can you please send me an invite to the Slack group? @jtktam

**Comment by JohnOCFII** [comment]
> Can you please send me an invite to the Slack group? @jtktam

If you leave us your email address, we can send you an invitation, @rdsmith24

**Comment by rdsmith24** [comment]
Sent you an email....

**Comment by bemojo** [comment]
Just put an order from misumi and I would also like to be invited to slack. Not so familiar with git, how do I send you a private msg with my mail?

**Comment by JohnOCFII** [comment]
> Just put an order from misumi and I would also like to be invited to slack. Not so familiar with git, how do I send you a private msg with my mail?

@bemojo - my email address is in my GitHub profile.  Click on my photo, and below that is my email address.

**Comment by JohnOCFII** [comment]
Today we announced our discussion forum transition from Slack to MatterMost.  The signup page is open to all (again).

It is at https://3dprinting.community/login

Hope to see you there!

John
