### ISSUE TITLE
Firmware says to change encoder steps, but ...

### ISSUE THREAD

**Issue by Tigwin** [PrusaMK2Users/3030_Haribo_Edition#35]
those values are already the default in the current version of the firmware. (.11)

**Comment by JohnOCFII** [comment]
3.0.11 was just released two days before your message.  We just don't move that fast around here -- day jobs, you know. :)

Thanks for the point out.

**Comment by Tigwin** [comment]
I'm aware. Just making a note its out of date now.  Its one less thing to configure.
