### ISSUE TITLE
Reduce vertical size of LCD cover opening

### ISSUE THREAD

**Issue by stevenkuiper** [PrusaMK2Users/3030_Haribo_Edition#7]
The opening of the LCD cover is larger than it needs to be.  Bottom of opening aligns correctly with LCD, but the top extends too far.  Will add exact dimensions asap.

**Comment by rob5standingby** [comment]
@stevenkuiper Closing this one and consolidating all of the problems with the LCD cover into one single issue. https://github.com/PrusaMK2Users/3030_Haribo_Edition/issues/10

**Comment by rob5standingby** [comment]
See https://github.com/PrusaMK2Users/3030_Haribo_Edition/issues/10 for details!
