### ISSUE TITLE
source files

### ISSUE THREAD

**Issue by tcurdt** [PrusaMK2Users/3030_Haribo_Edition#75]
It seems like this repo only has the STL files.
Where are the source files?
What am I missing?

**Comment by Tigwin** [comment]
Welcome to 3d printing. You'll find that most projects release stl files, Prusa included. Anything based on a stl, would obviously also be a stl.

**Comment by tcurdt** [comment]
@Tigwin Indeed everything gets exported to STL in the 3d printing world - but hardly anyone uses that as the source format. 

Prusa uses OpenSCAD to model the parts and then exports them to STLs. [The scad files are also available](https://github.com/prusa3d/Original-Prusa-i3/tree/MK2/Printed-Parts). Other people use Fusion360, Blender or even SolidWorks to model their parts.

**Comment by SkyDriver2k4** [comment]
the most parts are on jtktams tinkercad. my own files are on fusion. so if you wish to change anything or get access to it. just ask for it on mattermost ~haribo3030 channel.
