### ISSUE TITLE
Can we get the original CAD files?

### ISSUE THREAD

**Issue by metacollin** [PrusaMK2Users/3030_Haribo_Edition#80]
Providing a bunch of .STL files is analogous to providing binaries alone.  Where are the .scad files that were used to generate the STL files?  Or, if OpenSCAD wasn't used, where are the original design files in whatever CAD program that was originally used?   

You license this under the GPL, but in every way that matters, this project is closed source.  It is definitely arguable that this repo is in violation of the GPL, as the files needed to generate the .STL files are not available, but you've clearly used some of the prusa .scad file code in parts to create new .STL file variations for this mod.  

Case in point:  there is an error in the L and T brackets.  In the T bracket, two of the holes have a very low poly count set (which would only be an issue for something created in OpenSCAD...so where is the .scad _**source code?**_), while all of the holes are like this in the L bracket.  

Since this project is not open source, I cannot easily fix what should be a trivial change.  I would change one '$fn =' statement and be done.  But I can't, because you haven't included the source.  I also can't do a pull request of said change and contribute to the repository.  

My only option would be to recreate the .scad source independently which will not necessarily be the same code at all, and only produce something functionally equivalent.  

This is how you can tell if something isn't open source, if people have to literally do the exact same thing as the reason behind linux even existing (it was to make a functional clone of unix, back when unix was closed source), then it isn't open source.  

I request the inclusion of the CAD source files, or links to non-private tinkercad projects (or whatever else cloud-based service that might have been used), for every .STL included in this repo that is in some way derived from the original Prusa design.  At the very least to be in the spirit of the GPL, if not in actual compliance with it.  

I know the people maintaining this repo may not have these files themselves.  It it still your responsibility to contact the people that do, and acquire them for the inclusion in this repository.

**Comment by Tigwin** [comment]
Hey smart guy. What if the designs were made in tinkercad, and they export as stl's?

**Comment by metacollin** [comment]
Then do this: https://metacollin.com/screens/upshot_fFHvB2p4.png

And provide links in a text file.

**Comment by Tigwin** [comment]
You'll still just get a stl from it.

**Comment by metacollin** [comment]
No, you get a copy of the actual tinkercad project in tinkercad, allowing you make edits to the original raw objects, which you can export as an STL.   

I would be able to ungroup the L bracket for example, find the low poly cylinder holes, edit them, regroup, and rexport a new STL.

I cannot do this as you've not provided me a means to, which you are legally obligated to do due to the GPL.

I'm literally trying to contribute to the Haribo 3030 project, I have one built on my desk right now, so what is this resistance?  I'm giving you a very real, practical example of how the current situation is both impeding this project, and is not in the spirit of open source.  I'm sorry if you don't like that, but I would like to made several improvements (which you are of course welcome to deny/otherwise say they aren't improvements) but I can't without the means of editing the original CAD model.  Fortunately, even Tinkercad provides a means of achieving this.  

Please work with me on this.  I apologize if I came off as overly hostile.  I probably should have approached this better.

**Comment by metacollin** [comment]
Here, maybe this will make it a little clearer:  If I have a link to a public Tinkercad project, I can click 'copy and tinker', and I get all the original individual objects used to create the model, grouped or ungrouped, and can easily edit them.  https://metacollin.com/screens/upshot_ysrrJqiv.png

On the other hand, I lose all of this information and cannot easily make any changes if I instead simply import a raw .stl file into Tinkercad: https://metacollin.com/screens/upshot_kEdUsQXH.png

Its analogous to how you can, technically, edit the raw machine code of a .exe, but that isn't the same as having access to the original means of editing and design, which in the case of a .exe, is the source code.  In this case, it would be tinkercad projects, or fusion 360 projects, or .scad files, or what have you.  Even if they cannot be directly included in the project repo, the means to acquire them (like on tinkercad) in a README somewhere would be enough for compliance.  And extremely helpful.  

Sorry, I probably am not helping to motivate the powers that be.  This project is awesome, I love my 3030 mod, and i've made my own MK2.5/MK3-ish version with an Einsy.  I was just somewhat disappointed to discover that there were no .scad (or whatever) files, and I had just assumed they were there until I actually needed to edit or 'remix' something.

**Comment by JohnOCFII** [comment]
Just to confirm.  The Haribo 3030 parts were designed in TinkerCAD.  There is no other CAD source.

**Comment by metacollin** [comment]
Excuse me, we both know this is nonsense.  You can provide links to the tinker cad projects and make them public,

**Comment by jtktam** [comment]
i choose not to make my tinkercad projects public, the stl files is what i started with and stl file plus the bom and documentation is what i am releasing.  it does not, as wrongfully alleged by you, violate the gpl and it’s not the same as binary files and source code..

also this design has zero to do with prusa.. so stop trying to make it an issue
